import { useState } from "react";
import { useParams } from "wouter";
import { useQuery } from "@tanstack/react-query";
import { RefreshCw, Copy, Check } from "lucide-react";
import { Card } from "@/components/kit";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import type { Podcast, RssFeed } from "@shared/schema";

/**
 * /shows/:id/rss-migration — walk a creator through pointing their old feed
 * at the Podlogix-hosted one. We can already show the destination feed URL
 * for real (it's generated by Podlogix); actually redirecting the *source*
 * host's feed is a manual step on their end, so this stays instructional.
 */
export default function ShowRssMigration() {
  const { id } = useParams<{ id: string }>();
  const [currentFeedUrl, setCurrentFeedUrl] = useState("");
  const [copied, setCopied] = useState(false);

  const { data: podcast } = useQuery<Podcast>({
    queryKey: ["/api/podcasts", id],
    queryFn: async () => {
      const res = await fetch(`/api/podcasts/${id}`);
      if (!res.ok) throw new Error("not found");
      return res.json();
    },
    enabled: !!id,
    retry: false,
  });

  const { data: rssFeeds } = useQuery<RssFeed[]>({
    queryKey: ["/api/podcasts", id, "rss"],
    queryFn: async () => {
      const res = await fetch(`/api/podcasts/${id}/rss`);
      if (!res.ok) return [];
      return res.json();
    },
    enabled: !!id,
    retry: false,
  });

  const podlogixFeed = (Array.isArray(rssFeeds) ? rssFeeds : []).find((f) => f.sourceType === "podlogix");
  const destinationUrl =
    podlogixFeed?.feedUrl || (id ? `${window.location.origin}/feeds/${id}/feed.xml` : "");

  const handleCopy = () => {
    if (!destinationUrl) return;
    navigator.clipboard.writeText(destinationUrl);
    setCopied(true);
    setTimeout(() => setCopied(false), 1500);
  };

  return (
    <div className="w-full max-w-2xl px-6 py-8">
      <h1 className="flex items-center gap-2 text-2xl font-semibold tracking-tight text-zinc-950">
        <RefreshCw size={20} className="text-zinc-400" />
        Move My Podcast Feed
      </h1>
      <p className="mt-1 mb-6 text-sm text-zinc-500">
        Migrate {podcast?.title ? `"${podcast.title}"` : "your show"}'s RSS feed to Podlogix with a redirect from your current host.
      </p>

      <Card padding="lg" className="space-y-5">
        <div>
          <label className="mb-1.5 block text-sm font-medium text-zinc-950">Your Current RSS Feed URL</label>
          <Input
            value={currentFeedUrl}
            onChange={(e) => setCurrentFeedUrl(e.target.value)}
            placeholder="https://media.example.com/your-podcast/feed.xml"
          />
          <p className="mt-1 text-xs text-zinc-400">Enter the RSS feed URL from your current podcast host.</p>
        </div>

        <div className="rounded-lg border border-zinc-100 bg-zinc-50/60 p-3">
          <p className="mb-1.5 text-xs font-medium text-zinc-600">Your new Podlogix RSS feed will be:</p>
          <div className="flex items-center gap-2">
            <code className="flex-1 truncate rounded-md bg-white px-2.5 py-1.5 text-xs text-zinc-700 border border-zinc-200">
              {destinationUrl || "—"}
            </code>
            <Button size="icon" variant="outline" className="h-8 w-8 shrink-0" onClick={handleCopy}>
              {copied ? <Check size={13} /> : <Copy size={13} />}
            </Button>
          </div>
        </div>

        <p className="text-xs text-zinc-400">
          Once you've confirmed the destination feed, set up a 301 redirect from your current feed URL to the one
          above with your existing host. This keeps subscribers on every app moving over automatically without
          losing ratings or reviews.
        </p>

        <Button className="w-full" disabled={!currentFeedUrl || !destinationUrl}>
          Continue
        </Button>
      </Card>
    </div>
  );
}
